"""Initial migration

Revision ID: df5a6411b31e
Revises: 
Create Date: 2026-01-15 18:17:34.388728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df5a6411b31e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('language_code', sa.String(length=10), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.Column('premium_until', sa.DateTime(), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('clones',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('personality_profile', sa.JSON(), nullable=False),
    sa.Column('accuracy_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('diaries_count', sa.Integer(), nullable=True),
    sa.Column('last_diary_at', sa.DateTime(), nullable=True),
    sa.Column('total_words_analyzed', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('training_stage', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_trained_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clones_id'), 'clones', ['id'], unique=False)
    op.create_index(op.f('ix_clones_user_id'), 'clones', ['user_id'], unique=False)
    op.create_table('diaries',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('clone_id', sa.BigInteger(), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('audio_file_path', sa.String(length=500), nullable=True),
    sa.Column('audio_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('analysis_result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(), nullable=True),
    sa.Column('analysis_version', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['clone_id'], ['clones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diaries_clone_id'), 'diaries', ['clone_id'], unique=False)
    op.create_index(op.f('ix_diaries_id'), 'diaries', ['id'], unique=False)
    op.create_index(op.f('ix_diaries_user_id'), 'diaries', ['user_id'], unique=False)
    op.create_table('clone_memories',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('clone_id', sa.BigInteger(), nullable=False),
    sa.Column('source_diary_id', sa.BigInteger(), nullable=True),
    sa.Column('memory_type', sa.String(length=50), nullable=False),
    sa.Column('memory_content', sa.Text(), nullable=False),
    sa.Column('memory_context', sa.Text(), nullable=True),
    sa.Column('importance_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clone_id'], ['clones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_diary_id'], ['diaries.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clone_memories_clone_id'), 'clone_memories', ['clone_id'], unique=False)
    op.create_index(op.f('ix_clone_memories_id'), 'clone_memories', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clone_memories_id'), table_name='clone_memories')
    op.drop_index(op.f('ix_clone_memories_clone_id'), table_name='clone_memories')
    op.drop_table('clone_memories')
    op.drop_index(op.f('ix_diaries_user_id'), table_name='diaries')
    op.drop_index(op.f('ix_diaries_id'), table_name='diaries')
    op.drop_index(op.f('ix_diaries_clone_id'), table_name='diaries')
    op.drop_table('diaries')
    op.drop_index(op.f('ix_clones_user_id'), table_name='clones')
    op.drop_index(op.f('ix_clones_id'), table_name='clones')
    op.drop_table('clones')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
